// <auto-generated />
namespace passionP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productbrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productbrand));
        
        string IMigrationMetadata.Id
        {
            get { return "202106040214024_product-brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
